### ISSUE TITLE
ElixirLS server constantly crashing

### ISSUE THREAD

**Issue by joeellis** [JakeBecker/vscode-elixir-ls#46]
I'm running into the dreaded `The ElixirLS server crashed 5 times in the last 3 minutes. The server will not be restarted` error message and not clear on why.

I had previously hit this issue and found a solution in https://github.com/JakeBecker/vscode-elixir-ls/issues/4 by setting a `ERL_LIB` var in my environment.  I am using `asdf-elixir`, so I had it set to 

```
/Users/joe/.asdf/installs/elixir/1.6.1/lib/elixir/lib
``` 

which I think it the correct path for `asdf-elixir` installs on a mac. but, for the past couple of days, the error seems to have returned and I can't seem to find the solution.  Are there any other known fixes for this error that I could try?

Side note: this plugin is truly fantastic, I've really been enjoying over the past month.

**Comment by JakeBecker** [comment]
I've just published a new release that has some bug fixes, so give that a try. If it still fails, please add the info from this issue template: https://github.com/JakeBecker/elixir-ls/blob/master/ISSUE_TEMPLATE.md

**Comment by joeellis** [comment]
@JakeBecker Thanks for this - the new version didn't work, but while going through the issue template, I found the error in the elixirLS logs.  It was related to some environment vars not getting loaded properly on that particular project.  Something I probably need to take care of in some separate vscode config, but not this plugin.  Thanks for the help!

**Comment by JakeBecker** [comment]
Btw, I just fixed a bug that caused the server to fail to launch on some projects. Try updating to v0.2.14 and with luck that might have fixed it.

**Comment by joeellis** [comment]
@JakeBecker Fantastic! You're right, I just upgraded and this latest update actually fixed it without me having to change anything else in vscode.  Well done!

**Comment by j-manu** [comment]
I'm still facing this issue.  I'm able to run `startserver.sh` from the extension directory so this is probably related to some environment variables not being set as I'm using asdf to manage elixir.  How can I view the "elixirLS logs" ?

**Comment by j-manu** [comment]
Also what's the way to completely wipe the installation and start anew? Uninstalling still leaves the extension directory in place. I removed the extension directory manually but some state seems to persist even then. When I installed first time, there was a message "server is being installed. it might take some time" and "server installed to 'location'" (not exact wording) but those messages never reappear after reinstalling

**Comment by JakeBecker** [comment]
It saves the PLT file to your Mix home, usually `~/.mix`, but that's unlikely to cause it to crash on start. Please open a new issue and add the information from this template: https://github.com/JakeBecker/elixir-ls/blob/master/ISSUE_TEMPLATE.md

**Comment by j-manu** [comment]
It was failing because `"elixirLS.projectDir`  value started with a '/'. Removing that fixed the issue. 

Thank you for this plugin. It's really good :)

**Comment by tiotolstoy** [comment]
Still having this issue on MacOS despite reading the fixes in issues. Getting the `The ElixirLS server crashed 5 times in the last 3 minutes. The server will not be restarted.` error. 

I installed Elixir/Erlang using asdf. What can I do?

**Comment by delameko** [comment]
@tiotolstoy You need to find out what the actual error message is.  If you go to View Menu > Output, then select ElixirLS from the little dropdown on the right-hand side, it'll show you what's causing it to crash.

**Comment by samtechie** [comment]
Got the same problem on Mac OS. Couldn't see any output.

**Comment by jejuro** [comment]
The same issue on Mac OS. ElixirLS Fork 0.2.26.
